name: Deploy to EKS
on:
  push:
    paths:
      - 'k8s/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AKIAX3NVJFI7AU66L74C }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name devops-eks --region us-west-1
      - name: Deploy to EKS
        run: kubectl apply -f k8s/
