name: Docker Build & Push
on:
  push:
    paths:
      - 'app/**'
      - 'Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Docker image
        run: docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
      - name: Push Docker image
        run: docker push ${{ secrets.ECR_REPOSITORY }}:latest
