name: Deploy to EKS
on:
  push:
    paths:
      - 'k8s/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAX3NVJFI7AU66L74C
          aws-secret-access-key: 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
          aws-region: us-west-1
      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region us-west-1 --name devops-eks
      - name: Deploy Service to EKS
        run: kubectl apply -f k8s/service.yaml
      - name: Deploy Deployment to EKS
        run: kubectl apply -f k8s/deployment.yaml
      - name: Deploy Ingress to EKS
        run: kubectl apply -f k8s/ingress.yaml
